name: DFSmpPlus
version: '1.0.0'
main: uk.co.nikodem.dFSmpPlus.DFSmpPlus
api-version: '1.21.3'
author: 'deadfry42'
commands:
  givedf:
    description: "Gives DFMaterial."
    usage: /givedf {item}
  dfmaterialview:
    description: "used for GeyserMC Rainbow"
    usage: /dfmaterialview
  test:
    description: "Test"
    usage: /test