name: DFSmpPlus
version: '1.0.0'
main: uk.co.nikodem.dFSmpPlus.DFSmpPlus
api-version: '1.21.3'
author: 'deadfry42'
depend: [UltimateAdvancementAPI]
commands:
  givedf:
    description: "Gives DFMaterial."
    usage: /givedf {item}
  dfmaterialview:
    description: "used for GeyserMC Rainbow"
    usage: /dfmaterialview
  test:
    description: "Test"
    usage: /test
  spawn:
    description: "Sends you to the spawn location of the server"
    usage: /spawn
    aliases: ["tptospawn", "tpspawn", "tospawn"]
  bin:
    description: "Open a GUI where you can throw things away"
    usage: /bin
    aliases: ["trash", "rubbish", "garbage"]
  dfdebug:
    description: "debug commands"
    usage: /dfdebug